# Generated by Django 5.1.3 on 2024-12-06 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course_instructor_enrollment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('created_date', 'id'), 'verbose_name_plural': 'Courses'},
        ),
    ]
