# Generated by Django 5.1.3 on 2024-12-20 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_course_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('frontend', 'Frontend Development'), ('backend', 'Backend Development'), ('data_science', 'Data Science'), ('machine', 'Machine Learning'), ('artificial', 'Artificial Intelligence'), ('ui', 'DUI/UX Design')], default='backend', max_length=30),
        ),
    ]
