# Generated by Django 5.1.4 on 2024-12-28 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_playlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('frontend', 'Frontend Development'), ('backend', 'Backend Development'), ('data_science', 'Data Science'), ('machine', 'Machine Learning'), ('artificial', 'Artificial Intelligence'), ('ui', 'UI/UX Design')], default='backend', max_length=30),
        ),
    ]
