# Generated by Django 5.1.3 on 2024-12-28 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_alter_course_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='video_url',
            field=models.CharField(max_length=200),
        ),
    ]
