
# This is a basic workflow to help you get started with Actions

name: Online-Courses-CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env: 
  filepath: c:\temp\version-prod.txt    
jobs:
  
  build:
    runs-on: django
    
    steps:
    - name: set version
      run: |       
       if (!(Test-Path $env:filepath)) {
        echo '0' > $env:filepath
       }
       $version=[int](cat $env:filepath) + 1
       echo $version > $env:filepath
       echo "version is $version"
      shell: pwsh   
      
    - name: show version
      run: |                
         $version=(cat $env:filepath)
         echo "version is $version"
      shell: pwsh
    - uses: actions/checkout@v4
    - name: Copy database file
      run: |
        copy 'D:\SWE2025\e-learning\db.sqlite3' .
      shell: pwsh
    - name: Build the Docker image
      run: |
        $version=(cat $env:filepath)
        docker build . --file Dockerfile --tag e-learning-prod:$version
      shell: pwsh
    - name: Clean up existing container
      run: |  
        if (docker ps -a --format '{{.Names}}' | Select-String -Pattern 'e-learning-prod') {
          docker stop e-learning-prod
          docker rm e-learning-prod
        }
      shell: pwsh
    - name: Run the Docker container
      run: |  
        $version=(cat $env:filepath)
        docker run -d -p 8000:8000 --name e-learning-prod e-learning-prod:$version
      shell: pwsh
