name: Online-Courses-CD
on:  
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env: 
  filepath: c:\temp\version-prod.txt    
jobs:
  
  build:
    runs-on: django
    
    steps:
    - name: set version
      run: |       
       if (!(Test-Path $env:filepath)) {
        echo '0' > $env:filepath
       }
       $version=[int](cat $env:filepath) + 1
       echo $version > $env:filepath
       echo "version is $version"
      shell: pwsh   
      
    - name: show version
      run: |                
         $version=(cat $env:filepath)
         echo "version is $version"
      shell: pwsh
    
    - name: Build the Docker image
      run: |
        $version=(cat $env:filepath)
        docker build . --file Dockerfile --tag e-learning-prod:$version
      shell: pwsh
    
    - name: Clean up existing container
      run: |  
        if (docker ps -a --format '{{.Names}}' | Select-String -Pattern 'e-learning-prod') {
          docker stop e-learning-prod
          docker rm e-learning-prod
        }
      shell: pwsh
    
    - name: Run the Docker container
      run: |  
        $version=(cat $env:filepath)
        docker run -d -p 8000:8000 -v D:\SWE2025\database-prod:/app/data --name e-learning-prod e-learning-prod:$version
      shell: pwsh
