name: online-courses-CI
on:
  push:
    branches: [ "testing" ]
  pull_request:
    branches: [ "testing" ]
  workflow_dispatch:

env: 
  filepath: c:\temp\version-testing.txt    
jobs:
  
  build:
    runs-on: django
    
    steps:
    - uses: actions/checkout@v4
    - name: set version
      run: |       
       if (!(Test-Path $env:filepath)) {
        echo '0' > $env:filepath
       }
       $version=[int](cat $env:filepath) + 1
       echo $version > $env:filepath
       echo "version is $version"
      shell: pwsh   
      
    - name: show version
      run: |                
         $version=(cat $env:filepath)
         echo "version is $version"
      shell: pwsh

    - name: Build the Docker image
      run: |
        $version=(cat $env:filepath)
        docker build . --file Dockerfile --tag e-learning-testing:$version
      shell: pwsh
    
    - name: Clean up existing container
      run: |  
        if (docker ps -a --format '{{.Names}}' | Select-String -Pattern 'e-learning-testing') {
          docker stop e-learning-testing
          docker rm e-learning-testing
        }
      shell: pwsh
    
    - name: Run the Docker container
      run: |  
        $version=(cat $env:filepath)
        docker run -d -p 7000:8000 -v D:\SWE2025\database-testing:/app/data --name e-learning-testing e-learning-testing:$version
      shell: pwsh
