name: online-courses-CI
on:
  push:
    branches: [ "testing" ]
  pull_request:
    branches: [ "testing" ]
  workflow_dispatch:
jobs:
  
  build:
    runs-on: django
    
    steps:
    - uses: actions/checkout@v4
    - name: Get Image Tag
      run:
        $timestamp = (Get-Date -UFormat "%s");
        echo "Generated timestamp :" $timestamp;
        echo "timestamp=$timestamp" >> $GITHUB_ENV;
        echo "1 The timestamp is ${{ env.timestamp }}"
      shell: pwsh
    - name: Verify Timestamp
      run: |
        echo "2 The timestamp is ${{ env.timestamp }}"
      shell: pwsh
    - name: Build the Docker image
      run:        
        docker build . --file Dockerfile --tag e-learning:${{ env.timestamp }}
      shell: pwsh
    - name: Clean up existing container
      run:
        if (docker ps -a --format '{{.Names}}' | Select-String -Pattern 'e-learning-testing') {
          docker stop e-learning-testing
          docker rm e-learning-testing
        }
      shell: pwsh
    - name: Run the Docker container
      run:
        $timestamp = (Get-Date -UFormat "%s")
        docker run -d -p 7000:8000 --name e-learning-testing e-learning:${{ env.timestamp }}
      shell: pwsh
